### ISSUE TITLE
service and protocol update support missing for SRV record

### ISSUE THREAD

**Issue by sakthishanmugam02** [IBM/dns-svcs-go-sdk#6]
Terraform is not updating service and protocol information due to missing update support for these fields in SDK.

Reference: 
CREATE: 
https://github.com/IBM/dns-svcs-go-sdk/blob/master/dnssvcsv1/dns_resource_records.go#L137
UPDATE: (missing)
https://github.com/IBM/dns-svcs-go-sdk/blob/master/dnssvcsv1/dns_resource_records.go#L270

**Comment by hughhuangzh** [comment]
close this issue for new build release.
